name: Deploy n8n Workflows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy workflows to n8n
        env:
          N8N_API_URL: https://n8n-test.n8n.cactus.eks.aws.theiconic.com.au
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: |
          for file in workflows/*.json; do
            echo "Deploying $file"
            curl -X POST $N8N_API_URL/workflows \
              -H "Authorization: Bearer $N8N_API_KEY" \
              -H "Content-Type: application/json" \
              -d @"$file"
          done
